### ISSUE TITLE
Tested on the real hardware tft display?

### ISSUE THREAD

**Issue by overheat** [IniterWorker/gc9a01#1]
Looking forward to know. :)

**Comment by IniterWorker** [comment]
Hi @overheat,

I apologize for not having much time to complete this library. The Chinese documentation didn't provide many details about the initialization process. I received my hardware order just a few weeks ago.

If you're interested in contributing, the work needs to be done at this location: [GitHub link](https://github.com/IniterWorker/gc9a01/blob/93a710c98e3cd2e10a86ae503c26b2413ba8df5e/gc9a01/src/display.rs#L51). Please feel free to contribute to the project."

Let me know if you need any further assistance!

**Comment by overheat** [comment]
Good to know you have received it. I did't place my order yet.
Do you have some example code in other programming language as reference?

**Comment by IniterWorker** [comment]
A lot of libraries out there, but I think everyone copy&past without wondering how the init sequence work.
- [Exboom/GC9A01](https://github.com/Exboom/GC9A01/blob/master/Core/Src/GC9A01.c)
- [Waveshare gc9a01](https://www.waveshare.com/wiki/1.28inch_LCD_Module)

**Comment by IniterWorker** [comment]
@overheat, there are new commits on the master branch if you want to try it. See the blackpill-test.

I am working on fixing an issue with the display window.

**Comment by IniterWorker** [comment]
Tested on a real hardware. Crate available on https://crates.io/crates/gc9a01-rs.
