### ISSUE TITLE
Using with slint

### ISSUE THREAD

**Issue by rsov** [IniterWorker/gc9a01#5]
Hello, great library!

I am trying to use it with slint on esp32-s3 and I am getting `Exception occured 'LoadProhibited'` error

The funny thing is, my equivalent implementation of https://github.com/slint-ui/slint/blob/cadfd9e1041214021a375795df9ef96e45d14999/examples/mcu-board-support/esp32_s3_box.rs#L219 is 

```
display.clear();
display.flush().unwrap();
```

Do you have any ideas why this is happening?

If not, would it be worth while implementing `set_pixels` method in this driver like it is implemented in this one? https://github.com/almindor/st7789/blob/e18dc571c1e2adb56bf9c6511887845b852f69c6/src/lib.rs#L236

Thank you!

**Comment by IniterWorker** [comment]
Please provide more information:
- A minimal example to reproduce the issue.
- A precise request, for example, if you need a feature like `set_pixels`.

Please do not provide external exceptions such as:
> Exception occurred 'LoadProhibited'

At the library level, we cannot support issues caused by other libraries.

What are the requirements for `set_pixels` when `set_pixel` is already available with the buffered approach?

https://github.com/IniterWorker/gc9a01/blob/6b3ddc81c68e61b495825ab46a58a33a37bba1e9/src/mode/graphics.rs#L164

**Comment by rsov** [comment]
I think the key difference between `set_pixel` is that it changes data in the buffer, while `set_pixels` writes it straight to the device, line by line

Will try to submit minimal reproduceable example soon

**Comment by rsov** [comment]
In progress of stripping down everything, the exception went away but it's not displaying correctly

Here is what is expected:
![image](https://github.com/user-attachments/assets/6ef944bf-8571-4c9d-8ada-a3fdf028cadc)

Here is what I get:
Note the little line at the edge changes when background color is changed
![image](https://github.com/user-attachments/assets/c74174f9-5590-4bde-9ae1-1f1de6ec843d)

Branch with code:
https://github.com/rsov/rusty_bucket_face/blob/feature/slint/src/main.rs


I have tried changing rotation and replacing the example `fill_contiguous` code that yielded same results
```rust
for (i, pixel_color) in buffer.iter().enumerate() {
  self.display.set_pixel(i as _, line as _, pixel_color.0);
}
```

It almost feels like it's either rendering the very last bit or one of the axis is flipped

Any help with this is appreciated

**Comment by IniterWorker** [comment]
@rsov did you/could you display a basic  rectangle with embedded_graphics via https://github.com/IniterWorker/esp32-s3-touch-lcd-1-28/blob/d02db8cf16075181fba171390b3d3251ff3f2383/src/main.rs#L34 ?

1) Try to use the driver standalone, first to validate your setup.
2) Did you check for memory issues, stack/heap issue with double/triple allocation (slint + gc9a01 Buffered) of the `240*240*size_of(pixel_color)` ?

**Comment by rsov** [comment]
Yes the example code worked well with direct draw calls

Sorry, I am out of my depth when it comes to embedded environments and rust. What would be some good keywords to search for to get started?

**Comment by rsov** [comment]
You may have been on the right track with the double buffering issue

I have forked and added a method to send buffer data directly. It works... but the colors are all wrong and it lost the sharpness. Will see if it's possible to improve it further

https://github.com/rsov/gc9a01/blob/7f5a94657cf327b9a23a1a80a28fe015edc09cdd/src/driver.rs#L287

and i send data to it this way

```rust
self.display
        .send_line(&buffer.iter().map(|&x| x.0).collect::<Vec<u16>>())
        .unwrap();
```

![image](https://github.com/user-attachments/assets/4d05c364-f25f-44fc-b50c-0ef460fdb217)

**Comment by IniterWorker** [comment]
Please always provide an example. Mainly a color shift from your end with `map(|&x| x.0)`. But, I can't help you without more source.

EDIT

```rust
// Pure speculation
use embedded_graphics_core::pixelcolor::raw::RawU16;

self.display
        .send_line(&buffer.iter().map(|&x| RawU16::new(x.0).into()).collect::<Vec<RawU16>>())
        .unwrap();
```

**Comment by IniterWorker** [comment]
I am implementing the [esp32-s3-touch-lcd-1-28](https://github.com/IniterWorker/esp32-s3-touch-lcd-1-28) with `lvgl`. Currently, `lvgl` provides a specialized trait for drawing lines using `embedded_graphics` (https://github.com/lvgl/lv_binding_rust/blob/3b3abb3019eef637b932fae967a8d246bf5b6f14/lvgl/src/display.rs#L308).

It seems like a better approach for `slint` to offer such a trait as well.

**Comment by rsov** [comment]
@IniterWorker It does look somewhat similar. I think `slint` wants to write directly into buffer

I got it to work on my project but haven't had the time to fork your example code and port it there

**Comment by rsov** [comment]
@IniterWorker Got the example repo up https://github.com/rsov/esp_s3_touch_lcd_1_28_example_slint

See this commit in driver, gives direct access to the buffer https://github.com/rsov/gc9a01/commit/b1c71fe54611dbf2ac674ff8fd527d0605fef768 then it is [used here to send data to screen](https://github.com/rsov/esp_s3_touch_lcd_1_28_example_slint/blob/feffe5a2e05457ff7267d07d714e6a57fc39b787/src/main.rs#L153) in the example

I can open a PR for it but it does not feel like I have implemented it the correct way

**Comment by IniterWorker** [comment]
Seems like you are missing some commands https://github.com/rsov/gc9a01/commit/b1c71fe54611dbf2ac674ff8fd527d0605fef768 like `MemoryWrite`.

Maybe, I should provide an unbuffered driver to easly customize the driver implementation/usage. 

**NOTE:** You may encouter #8, I will fix this soon.

**Comment by rsov** [comment]
So I've tried [implementing](https://github.com/rsov/gc9a01/commit/1c0021f34eadd46775b563511426be2fe09fd0b6) `fill_contiguous` method  and then using it as it's written in [slint docs](https://docs.rs/slint/latest/slint/docs/mcu/index.html#rendering-line-by-line), going off the work done in this one https://github.com/IniterWorker/gc9a01/issues/8

And it works! 🚀 

But UI feels slower compared to just writing it directly like https://github.com/rsov/gc9a01/commit/b1c71fe54611dbf2ac674ff8fd527d0605fef768 because you have to flush buffer after each line. And this way doesn't do screen rotation and has endianness issues

I will see if I can make something like this method but public https://github.com/IniterWorker/gc9a01/blob/89adb341b8c6ed3c2d33e742ad9c609884174776/src/driver.rs#L265

Or this that accepts RBG color
https://github.com/IniterWorker/gc9a01/blob/89adb341b8c6ed3c2d33e742ad9c609884174776/src/driver.rs#L127

**Comment by IniterWorker** [comment]
> But UI feels slower compared to just writing it directly like https://github.com/rsov/gc9a01/commit/b1c71fe54611dbf2ac674ff8fd527d0605fef768 because you have to flush buffer after each line. And this way doesn't do screen rotation and has endianness issues

If you're looking for performance and direct access without buffering, I've made changes to the master branch. Could you please give it a try and provide some feedback?

```rust
let mut display_driver = Gc9a01::new(
        interface,
        DisplayResolution240x240,
        DisplayRotation::Rotate180,
    );
``` 

I added `graphics` feature too.

Here is an example with `lvgl` without `BufferedGraphics` a.k.a `BasicMode`.

```rust
let buffer = DrawBuffer::<{ 12 * 240_usize }>::default();
let display = Display::register(buffer, 240, 240, |refresh| {
    display_driver
        .fill_contiguous(
            &Rectangle::new(
                Point::new(refresh.area.x1.into(), refresh.area.y1.into()),
                Size::new(
                    (refresh.area.x2 - refresh.area.x1) as u32 + 1,
                    (refresh.area.y2 - refresh.area.y1) as u32 + 1,
                ),
            ),
            refresh
                .as_pixels::<Rgb565>()
                .into_iter()
                .map(|color| color.1),
        )
        .unwrap();
})
.unwrap();
```

**Comment by rsov** [comment]
@IniterWorker  Works like a charm!
